export const ENV_APIKEY = '<YOUR_APIKEY>';
export const ENV_AUTHDOMAIN = '<YOUR_AUTHDOMAIN>';
export const ENV_DATABASEURL = '<YOUR_DATABASEURL>';
export const ENV_STORAGEBUCKET = '<YOUR_STORAGEBUCKET>';